components:
  schemas:
    protobufAny:
      additionalProperties: { }
      properties:
        '@type':
          type: string
      type: object
    rpcStatus:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
        message:
          type: string
      type: object
  securitySchemes:
    OAuth2:
      flows:
        authorizationCode:
          scopes: { }
      type: oauth2
externalDocs:
  description: REST API for the Admin UI service
  url: https://github.com/canonical/identity-platform-admin-ui/blob/main/API.md
info:
  contact:
    name: Identity Platform Admin UI API
    url: https://github.com/canonical/identity-platform-admin-ui-api
  description: REST API for the Admin UI service
  license:
    name: BSD 3-Clause License
    url: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE
  title: Identity Platform Admin UI API
  version: "0.1"
openapi: 3.0.3
paths: null
