// Copyright 2025 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v0/schemas/model.proto

package schemas

import (
	http "github.com/canonical/identity-platform-api/v0/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema               *structpb.Struct `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	AdditionalProperties *structpb.Struct `protobuf:"bytes,3,opt,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schema) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Schema) GetAdditionalProperties() *structpb.Struct {
	if x != nil {
		return x.AdditionalProperties
	}
	return nil
}

type DefaultSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DefaultSchema) Reset() {
	*x = DefaultSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultSchema) ProtoMessage() {}

func (x *DefaultSchema) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultSchema.ProtoReflect.Descriptor instead.
func (*DefaultSchema) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultSchema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSchemasResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*Schema        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status  int32            `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string          `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Meta    *http.Pagination `protobuf:"bytes,4,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
}

func (x *ListSchemasResp) Reset() {
	*x = ListSchemasResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSchemasResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResp) ProtoMessage() {}

func (x *ListSchemasResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResp.ProtoReflect.Descriptor instead.
func (*ListSchemasResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListSchemasResp) GetData() []*Schema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSchemasResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListSchemasResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ListSchemasResp) GetMeta() *http.Pagination {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSchemaReq) Reset() {
	*x = GetSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaReq) ProtoMessage() {}

func (x *GetSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaReq.ProtoReflect.Descriptor instead.
func (*GetSchemaReq) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchemaReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*Schema `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status  int32     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string   `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *GetSchemaResp) Reset() {
	*x = GetSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResp) ProtoMessage() {}

func (x *GetSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResp.ProtoReflect.Descriptor instead.
func (*GetSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaResp) GetData() []*Schema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type CreateSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *CreateSchemaReq) Reset() {
	*x = CreateSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaReq) ProtoMessage() {}

func (x *CreateSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaReq.ProtoReflect.Descriptor instead.
func (*CreateSchemaReq) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSchemaReq) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type CreateSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*Schema `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status  int32     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string   `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *CreateSchemaResp) Reset() {
	*x = CreateSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaResp) ProtoMessage() {}

func (x *CreateSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaResp.ProtoReflect.Descriptor instead.
func (*CreateSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSchemaResp) GetData() []*Schema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdateSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema *Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *UpdateSchemaReq) Reset() {
	*x = UpdateSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaReq) ProtoMessage() {}

func (x *UpdateSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaReq.ProtoReflect.Descriptor instead.
func (*UpdateSchemaReq) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSchemaReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSchemaReq) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type UpdateSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []*Schema `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status  int32     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string   `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *UpdateSchemaResp) Reset() {
	*x = UpdateSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaResp) ProtoMessage() {}

func (x *UpdateSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaResp.ProtoReflect.Descriptor instead.
func (*UpdateSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSchemaResp) GetData() []*Schema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type RemoveSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveSchemaReq) Reset() {
	*x = RemoveSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSchemaReq) ProtoMessage() {}

func (x *RemoveSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSchemaReq.ProtoReflect.Descriptor instead.
func (*RemoveSchemaReq) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveSchemaReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *RemoveSchemaResp) Reset() {
	*x = RemoveSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSchemaResp) ProtoMessage() {}

func (x *RemoveSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSchemaResp.ProtoReflect.Descriptor instead.
func (*RemoveSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoveSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetDefaultSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *DefaultSchema `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status  int32          `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string        `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *GetDefaultSchemaResp) Reset() {
	*x = GetDefaultSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultSchemaResp) ProtoMessage() {}

func (x *GetDefaultSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultSchemaResp.ProtoReflect.Descriptor instead.
func (*GetDefaultSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{11}
}

func (x *GetDefaultSchemaResp) GetData() *DefaultSchema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetDefaultSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetDefaultSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdateDefaultSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema *DefaultSchema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *UpdateDefaultSchemaReq) Reset() {
	*x = UpdateDefaultSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDefaultSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultSchemaReq) ProtoMessage() {}

func (x *UpdateDefaultSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultSchemaReq.ProtoReflect.Descriptor instead.
func (*UpdateDefaultSchemaReq) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDefaultSchemaReq) GetSchema() *DefaultSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type UpdateDefaultSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *DefaultSchema `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status  int32          `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message *string        `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *UpdateDefaultSchemaResp) Reset() {
	*x = UpdateDefaultSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_schemas_model_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDefaultSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultSchemaResp) ProtoMessage() {}

func (x *UpdateDefaultSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v0_schemas_model_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultSchemaResp.ProtoReflect.Descriptor instead.
func (*UpdateDefaultSchemaResp) Descriptor() ([]byte, []int) {
	return file_v0_schemas_model_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDefaultSchemaResp) GetData() *DefaultSchema {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDefaultSchemaResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDefaultSchemaResp) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_v0_schemas_model_proto protoreflect.FileDescriptor

var file_v0_schemas_model_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x30, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x76, 0x30, 0x2f, 0x68, 0x74, 0x74,
	0x70, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x06,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x4c, 0x0a, 0x15, 0x61, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x14, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x40,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x88, 0x01, 0x01,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x72, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x42,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x22, 0x72, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x10, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x7d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x40, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x22, 0x80, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v0_schemas_model_proto_rawDescOnce sync.Once
	file_v0_schemas_model_proto_rawDescData = file_v0_schemas_model_proto_rawDesc
)

func file_v0_schemas_model_proto_rawDescGZIP() []byte {
	file_v0_schemas_model_proto_rawDescOnce.Do(func() {
		file_v0_schemas_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_v0_schemas_model_proto_rawDescData)
	})
	return file_v0_schemas_model_proto_rawDescData
}

var file_v0_schemas_model_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v0_schemas_model_proto_goTypes = []interface{}{
	(*Schema)(nil),                  // 0: Schema
	(*DefaultSchema)(nil),           // 1: DefaultSchema
	(*ListSchemasResp)(nil),         // 2: ListSchemasResp
	(*GetSchemaReq)(nil),            // 3: GetSchemaReq
	(*GetSchemaResp)(nil),           // 4: GetSchemaResp
	(*CreateSchemaReq)(nil),         // 5: CreateSchemaReq
	(*CreateSchemaResp)(nil),        // 6: CreateSchemaResp
	(*UpdateSchemaReq)(nil),         // 7: UpdateSchemaReq
	(*UpdateSchemaResp)(nil),        // 8: UpdateSchemaResp
	(*RemoveSchemaReq)(nil),         // 9: RemoveSchemaReq
	(*RemoveSchemaResp)(nil),        // 10: RemoveSchemaResp
	(*GetDefaultSchemaResp)(nil),    // 11: GetDefaultSchemaResp
	(*UpdateDefaultSchemaReq)(nil),  // 12: UpdateDefaultSchemaReq
	(*UpdateDefaultSchemaResp)(nil), // 13: UpdateDefaultSchemaResp
	(*structpb.Struct)(nil),         // 14: google.protobuf.Struct
	(*http.Pagination)(nil),         // 15: identity.platform.api.types.Pagination
}
var file_v0_schemas_model_proto_depIdxs = []int32{
	14, // 0: Schema.schema:type_name -> google.protobuf.Struct
	14, // 1: Schema.additional_properties:type_name -> google.protobuf.Struct
	0,  // 2: ListSchemasResp.data:type_name -> Schema
	15, // 3: ListSchemasResp.meta:type_name -> identity.platform.api.types.Pagination
	0,  // 4: GetSchemaResp.data:type_name -> Schema
	0,  // 5: CreateSchemaReq.schema:type_name -> Schema
	0,  // 6: CreateSchemaResp.data:type_name -> Schema
	0,  // 7: UpdateSchemaReq.schema:type_name -> Schema
	0,  // 8: UpdateSchemaResp.data:type_name -> Schema
	1,  // 9: GetDefaultSchemaResp.data:type_name -> DefaultSchema
	1,  // 10: UpdateDefaultSchemaReq.schema:type_name -> DefaultSchema
	1,  // 11: UpdateDefaultSchemaResp.data:type_name -> DefaultSchema
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v0_schemas_model_proto_init() }
func file_v0_schemas_model_proto_init() {
	if File_v0_schemas_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v0_schemas_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSchemasResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDefaultSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_schemas_model_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDefaultSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v0_schemas_model_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_v0_schemas_model_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v0_schemas_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v0_schemas_model_proto_goTypes,
		DependencyIndexes: file_v0_schemas_model_proto_depIdxs,
		MessageInfos:      file_v0_schemas_model_proto_msgTypes,
	}.Build()
	File_v0_schemas_model_proto = out.File
	file_v0_schemas_model_proto_rawDesc = nil
	file_v0_schemas_model_proto_goTypes = nil
	file_v0_schemas_model_proto_depIdxs = nil
}
